spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Route for product-service
            - id: product-service-route
              uri: lb://product-service
              predicates:
              - Path=/api/product/**
            # Route for order-service
            - id: order-service-route
              uri: lb://order-service
              predicates:
                - Path=/api/order/**
            # Route for discovery-service
            - id: discovery-service-route
              uri: http://localhost:8761
              predicates:
                - Path=/eureka/web
              filters:
                - StripPrefix=2
            # Route for discovery-service Static Resources
            - id: discovery-service-route-static
              uri: http://localhost:8761
              predicates:
                - Path=/eureka/**
            # Route for /api/docs/products to product-service /v3/api-docs
            - id: api-docs-product-service-route
              uri: lb://product-service
              predicates:
                - Path=/product/api-docs
              filters:
                - RewritePath=/product/api-docs,/v3/api-docs
            # Route for /api/docs/order to order-service /v3/api-docs
            - id: api-docs-order-service-route
              uri: lb://order-service
              predicates:
                - Path=/order/api-docs
              filters:
                - RewritePath=/order/api-docs,/v3/api-docs
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-boot-microservices-realm
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost

server:
  port: 8182

logging:
  level:
    root: info
    org:
      springframework:
        cloud:
          gateway: TRACE
    com:
      netflix:
        discovery: DEBUG
